language: php

os:
  - linux

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

install:
    - composer self-update
    - composer install

script: vendor/bin/codecept run

